<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A55B63_huynhchinh307" Class="APIDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SQL5052.site4now.net;Initial Catalog=DB_A55B63_huynhchinh307;Persist Security Info=True;User ID=DB_A55B63_huynhchinh307_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_A55B63_huynhchinh307ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MISSION_PROCESS" Member="MISSION_PROCESSes">
    <Type Name="MISSION_PROCESS">
      <Column Name="id_employee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_mission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="EMPLOYEE_MISSION_PROCESS" Member="EMPLOYEE" ThisKey="id_employee" OtherKey="id_employee" Type="EMPLOYEE" IsForeignKey="true" />
      <Association Name="MISSION_MISSION_PROCESS" Member="MISSION" ThisKey="id_mission" OtherKey="id_mission" Type="MISSION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="id_employee" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_employee" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="point" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="level_employee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="apiKey" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="EMPLOYEE_MISSION_PROCESS" Member="MISSION_PROCESSes" ThisKey="id_employee" OtherKey="id_employee" Type="MISSION_PROCESS" />
      <Association Name="EMPLOYEE_MISSION" Member="MISSIONs" ThisKey="id_employee" OtherKey="id_employee" Type="MISSION" />
      <Association Name="EMPLOYEE_TYPE_MISSION" Member="TYPE_MISSIONs" ThisKey="id_employee" OtherKey="id_employee" Type="TYPE_MISSION" />
    </Type>
  </Table>
  <Table Name="dbo.MISSION" Member="MISSIONs">
    <Type Name="MISSION">
      <Column Name="id_mission" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_mission" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Stardate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="point" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exprie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="describe" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_employee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MISSION_MISSION_PROCESS" Member="MISSION_PROCESSes" ThisKey="id_mission" OtherKey="id_mission" Type="MISSION_PROCESS" />
      <Association Name="EMPLOYEE_MISSION" Member="EMPLOYEE" ThisKey="id_employee" OtherKey="id_employee" Type="EMPLOYEE" IsForeignKey="true" />
      <Association Name="TYPE_MISSION_MISSION" Member="TYPE_MISSION" ThisKey="id_type" OtherKey="id_type" Type="TYPE_MISSION" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TYPE_MISSION" Member="TYPE_MISSIONs">
    <Type Name="TYPE_MISSION">
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_type_mission" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_employee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TYPE_MISSION_MISSION" Member="MISSIONs" ThisKey="id_type" OtherKey="id_type" Type="MISSION" />
      <Association Name="EMPLOYEE_TYPE_MISSION" Member="EMPLOYEE" ThisKey="id_employee" OtherKey="id_employee" Type="EMPLOYEE" IsForeignKey="true" />
    </Type>
  </Table>
</Database>